version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dna_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7199:7199"